version: "3.8"

services:
  nginx:
  image: nginx:slim
  container_name: nginx-reverse-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./ngnix/default.conf:/etc/nginx/conf.d/default.conf:ro"
  # depends_on:
  #   - portfolio-site

  # TODO ADD portfolio-site