version: "3.8"

services:
  portfolio-site:
    build:
      context: /home/devsoham3/GitHappens/portfolio-site
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "3000:3000"  # Optional: only if you want direct access
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - portfolio-site
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: portfolio-network