version: "3.8"

services:
  portfolio-site:
    image: ghcr.io/devsoham3/portfolio-site:latest
    container_name: portfolio-app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # Enable HTTPS
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./certbot/conf:/etc/letsencrypt:ro"
      - "./certbot/www:/var/www/certbot"
    depends_on:
      - portfolio-site
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    command: certonly --webroot --webroot-path=/var/www/certbot --email devsoham3@gmail.com --agree-tos --no-eff-email -d portfolio.sohamdeo.com
    depends_on:
      - nginx

# Monitoring

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3001:3000"   # Exposes Grafana at http://<your-linode>:3001
    networks:
      - monitoring-network

networks:
  app-network:
    driver: bridge
    name: portfolio-network
  monitoring-network:
    driver: bridge
    name: portfolio-monitor

volumes:
  grafana-storage: