version: "3.8"

services:
  portfolio-site:
    image: ghcr.io/devsoham3/portfolio-site:latest
    container_name: portfolio-app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - portfolio-site
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: portfolio-network