version: "3.8"

services:
  portfolio-site:
    image: ghcr.io/devsoham3/portfolio-site:latest
    container_name: portfolio-app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # Enable HTTPS
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./certbot/conf:/etc/letsencrypt:ro"
      - "./certbot/www:/var/www/certbot"
    depends_on:
      - portfolio-site
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    command: certonly --webroot --webroot-path=/var/www/certbot --email devsoham3@gmail.com --agree-tos --no-eff-email -d portfolio.sohamdeo.com
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
    name: portfolio-network