global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'  # Updated path
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    metrics_path: '/cadvisor/metrics'    # Updated path
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
